// Code generated by mockery v2.20.0. DO NOT EDIT.

package registry

import mock "github.com/stretchr/testify/mock"

// mockNewEtcdClientT is an autogenerated mock type for the newEtcdClientT type
type mockNewEtcdClientT struct {
	mock.Mock
}

type mockNewEtcdClientT_Expecter struct {
	mock *mock.Mock
}

func (_m *mockNewEtcdClientT) EXPECT() *mockNewEtcdClientT_Expecter {
	return &mockNewEtcdClientT_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: _a0
func (_m *mockNewEtcdClientT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// mockNewEtcdClientT_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type mockNewEtcdClientT_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//  - _a0 func()
func (_e *mockNewEtcdClientT_Expecter) Cleanup(_a0 interface{}) *mockNewEtcdClientT_Cleanup_Call {
	return &mockNewEtcdClientT_Cleanup_Call{Call: _e.mock.On("Cleanup", _a0)}
}

func (_c *mockNewEtcdClientT_Cleanup_Call) Run(run func(_a0 func())) *mockNewEtcdClientT_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *mockNewEtcdClientT_Cleanup_Call) Return() *mockNewEtcdClientT_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockNewEtcdClientT_Cleanup_Call) RunAndReturn(run func(func())) *mockNewEtcdClientT_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *mockNewEtcdClientT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// mockNewEtcdClientT_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type mockNewEtcdClientT_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//  - format string
//  - args ...interface{}
func (_e *mockNewEtcdClientT_Expecter) Errorf(format interface{}, args ...interface{}) *mockNewEtcdClientT_Errorf_Call {
	return &mockNewEtcdClientT_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *mockNewEtcdClientT_Errorf_Call) Run(run func(format string, args ...interface{})) *mockNewEtcdClientT_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockNewEtcdClientT_Errorf_Call) Return() *mockNewEtcdClientT_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockNewEtcdClientT_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *mockNewEtcdClientT_Errorf_Call {
	_c.Call.Return(run)
	return _c
}

// FailNow provides a mock function with given fields:
func (_m *mockNewEtcdClientT) FailNow() {
	_m.Called()
}

// mockNewEtcdClientT_FailNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailNow'
type mockNewEtcdClientT_FailNow_Call struct {
	*mock.Call
}

// FailNow is a helper method to define mock.On call
func (_e *mockNewEtcdClientT_Expecter) FailNow() *mockNewEtcdClientT_FailNow_Call {
	return &mockNewEtcdClientT_FailNow_Call{Call: _e.mock.On("FailNow")}
}

func (_c *mockNewEtcdClientT_FailNow_Call) Run(run func()) *mockNewEtcdClientT_FailNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockNewEtcdClientT_FailNow_Call) Return() *mockNewEtcdClientT_FailNow_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockNewEtcdClientT_FailNow_Call) RunAndReturn(run func()) *mockNewEtcdClientT_FailNow_Call {
	_c.Call.Return(run)
	return _c
}

// Logf provides a mock function with given fields: format, args
func (_m *mockNewEtcdClientT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// mockNewEtcdClientT_Logf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logf'
type mockNewEtcdClientT_Logf_Call struct {
	*mock.Call
}

// Logf is a helper method to define mock.On call
//  - format string
//  - args ...interface{}
func (_e *mockNewEtcdClientT_Expecter) Logf(format interface{}, args ...interface{}) *mockNewEtcdClientT_Logf_Call {
	return &mockNewEtcdClientT_Logf_Call{Call: _e.mock.On("Logf",
		append([]interface{}{format}, args...)...)}
}

func (_c *mockNewEtcdClientT_Logf_Call) Run(run func(format string, args ...interface{})) *mockNewEtcdClientT_Logf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockNewEtcdClientT_Logf_Call) Return() *mockNewEtcdClientT_Logf_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockNewEtcdClientT_Logf_Call) RunAndReturn(run func(string, ...interface{})) *mockNewEtcdClientT_Logf_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockNewEtcdClientT interface {
	mock.TestingT
	Cleanup(func())
}

// newMockNewEtcdClientT creates a new instance of mockNewEtcdClientT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockNewEtcdClientT(t mockConstructorTestingTnewMockNewEtcdClientT) *mockNewEtcdClientT {
	mock := &mockNewEtcdClientT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
