// Code generated by mockery v2.20.0. DO NOT EDIT.

package registry

import (
	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// MockDoguRegistry is an autogenerated mock type for the DoguRegistry type
type MockDoguRegistry struct {
	mock.Mock
}

type MockDoguRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguRegistry) EXPECT() *MockDoguRegistry_Expecter {
	return &MockDoguRegistry_Expecter{mock: &_m.Mock}
}

// Enable provides a mock function with given fields: dogu
func (_m *MockDoguRegistry) Enable(dogu *core.Dogu) error {
	ret := _m.Called(dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(*core.Dogu) error); ok {
		r0 = rf(dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguRegistry_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type MockDoguRegistry_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
//  - dogu *core.Dogu
func (_e *MockDoguRegistry_Expecter) Enable(dogu interface{}) *MockDoguRegistry_Enable_Call {
	return &MockDoguRegistry_Enable_Call{Call: _e.mock.On("Enable", dogu)}
}

func (_c *MockDoguRegistry_Enable_Call) Run(run func(dogu *core.Dogu)) *MockDoguRegistry_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*core.Dogu))
	})
	return _c
}

func (_c *MockDoguRegistry_Enable_Call) Return(_a0 error) *MockDoguRegistry_Enable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguRegistry_Enable_Call) RunAndReturn(run func(*core.Dogu) error) *MockDoguRegistry_Enable_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: name
func (_m *MockDoguRegistry) Get(name string) (*core.Dogu, error) {
	ret := _m.Called(name)

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*core.Dogu, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *core.Dogu); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDoguRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - name string
func (_e *MockDoguRegistry_Expecter) Get(name interface{}) *MockDoguRegistry_Get_Call {
	return &MockDoguRegistry_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockDoguRegistry_Get_Call) Run(run func(name string)) *MockDoguRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDoguRegistry_Get_Call) Return(_a0 *core.Dogu, _a1 error) *MockDoguRegistry_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguRegistry_Get_Call) RunAndReturn(run func(string) (*core.Dogu, error)) *MockDoguRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *MockDoguRegistry) GetAll() ([]*core.Dogu, error) {
	ret := _m.Called()

	var r0 []*core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*core.Dogu, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*core.Dogu); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguRegistry_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockDoguRegistry_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockDoguRegistry_Expecter) GetAll() *MockDoguRegistry_GetAll_Call {
	return &MockDoguRegistry_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockDoguRegistry_GetAll_Call) Run(run func()) *MockDoguRegistry_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDoguRegistry_GetAll_Call) Return(_a0 []*core.Dogu, _a1 error) *MockDoguRegistry_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguRegistry_GetAll_Call) RunAndReturn(run func() ([]*core.Dogu, error)) *MockDoguRegistry_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with given fields: name
func (_m *MockDoguRegistry) IsEnabled(name string) (bool, error) {
	ret := _m.Called(name)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguRegistry_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockDoguRegistry_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
//  - name string
func (_e *MockDoguRegistry_Expecter) IsEnabled(name interface{}) *MockDoguRegistry_IsEnabled_Call {
	return &MockDoguRegistry_IsEnabled_Call{Call: _e.mock.On("IsEnabled", name)}
}

func (_c *MockDoguRegistry_IsEnabled_Call) Run(run func(name string)) *MockDoguRegistry_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDoguRegistry_IsEnabled_Call) Return(_a0 bool, _a1 error) *MockDoguRegistry_IsEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguRegistry_IsEnabled_Call) RunAndReturn(run func(string) (bool, error)) *MockDoguRegistry_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: dogu
func (_m *MockDoguRegistry) Register(dogu *core.Dogu) error {
	ret := _m.Called(dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(*core.Dogu) error); ok {
		r0 = rf(dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockDoguRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//  - dogu *core.Dogu
func (_e *MockDoguRegistry_Expecter) Register(dogu interface{}) *MockDoguRegistry_Register_Call {
	return &MockDoguRegistry_Register_Call{Call: _e.mock.On("Register", dogu)}
}

func (_c *MockDoguRegistry_Register_Call) Run(run func(dogu *core.Dogu)) *MockDoguRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*core.Dogu))
	})
	return _c
}

func (_c *MockDoguRegistry_Register_Call) Return(_a0 error) *MockDoguRegistry_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguRegistry_Register_Call) RunAndReturn(run func(*core.Dogu) error) *MockDoguRegistry_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function with given fields: name
func (_m *MockDoguRegistry) Unregister(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguRegistry_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockDoguRegistry_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//  - name string
func (_e *MockDoguRegistry_Expecter) Unregister(name interface{}) *MockDoguRegistry_Unregister_Call {
	return &MockDoguRegistry_Unregister_Call{Call: _e.mock.On("Unregister", name)}
}

func (_c *MockDoguRegistry_Unregister_Call) Run(run func(name string)) *MockDoguRegistry_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDoguRegistry_Unregister_Call) Return(_a0 error) *MockDoguRegistry_Unregister_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguRegistry_Unregister_Call) RunAndReturn(run func(string) error) *MockDoguRegistry_Unregister_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockDoguRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDoguRegistry creates a new instance of MockDoguRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDoguRegistry(t mockConstructorTestingTNewMockDoguRegistry) *MockDoguRegistry {
	mock := &MockDoguRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
