version: "2"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2.5
    command: ["etcd","--listen-client-urls", "http://0.0.0.0:4001", "--advertise-client-urls", "http://0.0.0.0:4001"]
    ports:
      - "4001:4001"
      - "2379:2379"
  authorizedRegistry:
    container_name: authorizedRegistry
    image: registry:2
    volumes:
      - ./resources/compose-config/docker/daemon.json:/etc/docker/daemon.json:ro
      - ./resources/compose-config/docker/cert.pem:/etc/docker/cert.pem:ro
      - ./resources/compose-config/docker/cert.key:/etc/docker/cert.key:ro
      - ./resources/compose-config/docker/htpasswd:/auth/htpasswd:ro
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/docker/cert.pem
      - REGISTRY_HTTP_TLS_KEY=/etc/docker/cert.key

  anonymousRegistry:
    container_name: anonymousRegistry
    image: registry:2
    volumes:
      - ./resources/compose-config/docker/daemon.json:/etc/docker/daemon.json:ro
      - ./resources/compose-config/docker/cert.pem:/etc/docker/cert.pem:ro
      - ./resources/compose-config/docker/cert.key:/etc/docker/cert.key:ro
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/docker/cert.pem
      - REGISTRY_HTTP_TLS_KEY=/etc/docker/cert.key

  dind:
    container_name: dind
    image: docker:18.01.0-ce-dind
    ports:
      - "2375:2375"
    privileged: true
    volumes:
      - ./resources/compose-config/docker/daemon.json:/etc/docker/daemon.json:ro
      - ./resources/compose-config/docker/cert.pem:/etc/docker/cert.pem:ro
      - ./resources/compose-config/docker/cert.key:/etc/docker/cert.key:ro
    command: ["--tls", "--tlscert=/etc/docker/cert.pem", "--tlskey=/etc/docker/cert.key"]