// Code generated by mockery v2.20.0. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHttpServer is an autogenerated mock type for the HttpServer type
type MockHttpServer struct {
	mock.Mock
}

type MockHttpServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHttpServer) EXPECT() *MockHttpServer_Expecter {
	return &MockHttpServer_Expecter{mock: &_m.Mock}
}

// ListenAndServe provides a mock function with given fields:
func (_m *MockHttpServer) ListenAndServe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHttpServer_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type MockHttpServer_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
func (_e *MockHttpServer_Expecter) ListenAndServe() *MockHttpServer_ListenAndServe_Call {
	return &MockHttpServer_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe")}
}

func (_c *MockHttpServer_ListenAndServe_Call) Run(run func()) *MockHttpServer_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHttpServer_ListenAndServe_Call) Return(_a0 error) *MockHttpServer_ListenAndServe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHttpServer_ListenAndServe_Call) RunAndReturn(run func() error) *MockHttpServer_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockHttpServer) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHttpServer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHttpServer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//  - ctx context.Context
func (_e *MockHttpServer_Expecter) Shutdown(ctx interface{}) *MockHttpServer_Shutdown_Call {
	return &MockHttpServer_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockHttpServer_Shutdown_Call) Run(run func(ctx context.Context)) *MockHttpServer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHttpServer_Shutdown_Call) Return(_a0 error) *MockHttpServer_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHttpServer_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockHttpServer_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockHttpServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHttpServer creates a new instance of MockHttpServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHttpServer(t mockConstructorTestingTNewMockHttpServer) *MockHttpServer {
	mock := &MockHttpServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
