// Code generated by mockery v2.20.0. DO NOT EDIT.

package doguConf

import mock "github.com/stretchr/testify/mock"

// mockConfigReader is an autogenerated mock type for the configReader type
type mockConfigReader struct {
	mock.Mock
}

type mockConfigReader_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigReader) EXPECT() *mockConfigReader_Expecter {
	return &mockConfigReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0
func (_m *mockConfigReader) Get(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockConfigReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - _a0 string
func (_e *mockConfigReader_Expecter) Get(_a0 interface{}) *mockConfigReader_Get_Call {
	return &mockConfigReader_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *mockConfigReader_Get_Call) Run(run func(_a0 string)) *mockConfigReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockConfigReader_Get_Call) Return(_a0 string, _a1 error) *mockConfigReader_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigReader_Get_Call) RunAndReturn(run func(string) (string, error)) *mockConfigReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobal provides a mock function with given fields: _a0
func (_m *mockConfigReader) GetGlobal(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigReader_GetGlobal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobal'
type mockConfigReader_GetGlobal_Call struct {
	*mock.Call
}

// GetGlobal is a helper method to define mock.On call
//  - _a0 string
func (_e *mockConfigReader_Expecter) GetGlobal(_a0 interface{}) *mockConfigReader_GetGlobal_Call {
	return &mockConfigReader_GetGlobal_Call{Call: _e.mock.On("GetGlobal", _a0)}
}

func (_c *mockConfigReader_GetGlobal_Call) Run(run func(_a0 string)) *mockConfigReader_GetGlobal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockConfigReader_GetGlobal_Call) Return(_a0 string, _a1 error) *mockConfigReader_GetGlobal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigReader_GetGlobal_Call) RunAndReturn(run func(string) (string, error)) *mockConfigReader_GetGlobal_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockConfigReader interface {
	mock.TestingT
	Cleanup(func())
}

// newMockConfigReader creates a new instance of mockConfigReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockConfigReader(t mockConstructorTestingTnewMockConfigReader) *mockConfigReader {
	mock := &mockConfigReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
