// Code generated by mockery v2.20.0. DO NOT EDIT.

package doguConf

import mock "github.com/stretchr/testify/mock"

// MockFieldReader is an autogenerated mock type for the FieldReader type
type MockFieldReader struct {
	mock.Mock
}

type MockFieldReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFieldReader) EXPECT() *MockFieldReader_Expecter {
	return &MockFieldReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields:
func (_m *MockFieldReader) Read() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFieldReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockFieldReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockFieldReader_Expecter) Read() *MockFieldReader_Read_Call {
	return &MockFieldReader_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockFieldReader_Read_Call) Run(run func()) *MockFieldReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldReader_Read_Call) Return(_a0 string, _a1 error) *MockFieldReader_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFieldReader_Read_Call) RunAndReturn(run func() (string, error)) *MockFieldReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockFieldReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFieldReader creates a new instance of MockFieldReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFieldReader(t mockConstructorTestingTNewMockFieldReader) *MockFieldReader {
	mock := &MockFieldReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
