// Code generated by mockery v2.20.0. DO NOT EDIT.

package keys

import (
	rsa "crypto/rsa"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockEncrypter is an autogenerated mock type for the Encrypter type
type MockEncrypter struct {
	mock.Mock
}

type MockEncrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncrypter) EXPECT() *MockEncrypter_Expecter {
	return &MockEncrypter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: random, pub, msg
func (_m *MockEncrypter) Execute(random io.Reader, pub *rsa.PublicKey, msg []byte) ([]byte, error) {
	ret := _m.Called(random, pub, msg)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader, *rsa.PublicKey, []byte) ([]byte, error)); ok {
		return rf(random, pub, msg)
	}
	if rf, ok := ret.Get(0).(func(io.Reader, *rsa.PublicKey, []byte) []byte); ok {
		r0 = rf(random, pub, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader, *rsa.PublicKey, []byte) error); ok {
		r1 = rf(random, pub, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncrypter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEncrypter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//  - random io.Reader
//  - pub *rsa.PublicKey
//  - msg []byte
func (_e *MockEncrypter_Expecter) Execute(random interface{}, pub interface{}, msg interface{}) *MockEncrypter_Execute_Call {
	return &MockEncrypter_Execute_Call{Call: _e.mock.On("Execute", random, pub, msg)}
}

func (_c *MockEncrypter_Execute_Call) Run(run func(random io.Reader, pub *rsa.PublicKey, msg []byte)) *MockEncrypter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(*rsa.PublicKey), args[2].([]byte))
	})
	return _c
}

func (_c *MockEncrypter_Execute_Call) Return(_a0 []byte, _a1 error) *MockEncrypter_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncrypter_Execute_Call) RunAndReturn(run func(io.Reader, *rsa.PublicKey, []byte) ([]byte, error)) *MockEncrypter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockEncrypter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEncrypter creates a new instance of MockEncrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEncrypter(t mockConstructorTestingTNewMockEncrypter) *MockEncrypter {
	mock := &MockEncrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
